spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
            scope: user
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  web:
    resources:
      add-mappings: false
